### ISSUE TITLE
Deprecate the use of Wiki

### ISSUE THREAD

**Issue by bpires** [leticiadasilva/Hacktoberfest#23]
### Sugestão de melhoria:

O uso de Wikis no GitHub não permite a edição colaborativa por meio de PRs de outros usuários, sendo mais recomendado transpor o conteúdo da Wiki para o readme ou para várias páginas em markdown no repo. Dessa maneira, contribuidores também podem colaborar com o conteúdo.

**Comment by leticiadasilva** [comment]
Já foi atualizado, muito obrigada!
